In [2]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
df = df = pd.read_csv('C:/Users/Josica/Documents/ML/ML-Activities/Data Files/2. ST Academy - Classification models resource files/Classification preprocessed data Python.csv',header=0)
x=df[['price']]
y=df['Sold']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)


In [3]:
scaler = preprocessing.StandardScaler().fit(x_train)
x_train_s = scaler.transform(x_train)

In [4]:
scaler = preprocessing.StandardScaler().fit(x_test)
x_test_s = scaler.transform(x_test)

In [5]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=1)

In [6]:
clf_knn.fit(x_train_s,y_train)

KNeighborsClassifier(n_neighbors=1)

In [7]:
confusion_matrix(y_test,clf_knn.predict(x_test_s))

array([[32, 26],
       [22, 22]], dtype=int64)

In [8]:
accuracy_score(y_test,clf_knn.predict(x_test_s))

0.5294117647058824

In [9]:
clf_knn3 = KNeighborsClassifier(n_neighbors=3)
clf_knn3.fit(x_train_s,y_train)


KNeighborsClassifier(n_neighbors=3)

In [10]:
confusion_matrix(y_test,clf_knn3.predict(x_test_s))


array([[34, 24],
       [23, 21]], dtype=int64)

In [11]:
accuracy_score(y_test,clf_knn3.predict(x_test_s))

0.5392156862745098

1

In [27]:
from sklearn.model_selection import GridSearchCV

In [31]:
params = {'n_neighbors':[1,2,3,4,5,6,7,8,9,10]}

In [32]:
grid_search_CV = GridSearchCV(KNeighborsClassifier(),params)

In [33]:
grid_search_CV.fit(x_train_s,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [34]:
grid_search_CV.best_params_

{'n_neighbors': 7}

In [35]:
optimized_KNN = grid_search_CV.best_estimator_

In [37]:
y_test_pred = optimized_KNN.predict(x_test_s)

In [38]:
confusion_matrix(y_test,y_test_pred)

array([[30, 28],
       [20, 24]], dtype=int64)

In [39]:
accuracy_score(y_test,y_test_pred)

0.5294117647058824