In [1]:
pwd

'C:\\Users\\sakthi\\Documents\\ML\\ML-Activities'

In [2]:
import pandas as pd
import numpy as np 
import seaborn as sns

In [3]:
df = pd.read_csv('C:/Users/sakthi/Documents/ML/ML-Activities/Data Files/2. ST Academy - Classification models resource files/Classification preprocessed data Python.csv',header=0)

## Logistic Regession 

In [4]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop   
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98  \
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES   
0       5.480     11.19200        23  0.049347     0    4.0875            1  \
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

In [5]:
x=df[['price']]
#incase of multiple logistic regressions, x = df.loc[:,df.columns!='sold']

In [6]:
y=df['Sold']

In [7]:
x.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression 

In [10]:
cls_lrg = LogisticRegression()

In [11]:
cls_lrg.fit(x,y)

LogisticRegression()

In [12]:
cls_lrg.coef_

array([[-0.03571865]])

In [13]:
import statsmodels.api as sm

In [14]:
x_const = sm.add_constant(x)

In [15]:
import statsmodels.discrete.discrete_model as dm

In [16]:
logit = dm.Logit(y,x_const).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [17]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Sat, 15 Apr 2023   Pseudo R-squ.:                 0.01788
Time:                        20:04:36   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

## Prediction and Confusion Matrix

In [20]:
cls_lrg.predict_proba(x)

array([[0.56032285, 0.43967715],
       [0.53910688, 0.46089312],
       [0.6512781 , 0.3487219 ],
       ...,
       [0.55944269, 0.44055731],
       [0.54265485, 0.45734515],
       [0.51596437, 0.48403563]])

In [24]:
y_pred = cls_lrg.predict(x)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [26]:
y_pred_3 = (cls_lrg.predict_proba(x)[:,1]>=0.3)
y_pred_3

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [27]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y,y_pred)

array([[208,  68],
       [165,  65]], dtype=int64)

In [28]:
confusion_matrix(y,y_pred_3)

array([[ 29, 247],
       [  2, 228]], dtype=int64)

# Perfomance metrics



In [57]:
from sklearn.metrics import precision_score,recall_score,roc_auc_score,accuracy_score

In [36]:
precision_score(y,y_pred)

0.48872180451127817

In [37]:
recall_score(y,y_pred)

0.2826086956521739

In [40]:
roc_auc_score(y,y_pred)

0.5181159420289855

# Test-Train Split

In [42]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [45]:
model = LogisticRegression()

In [46]:
model.fit(x_train,y_train)

LogisticRegression()

In [53]:
y_test_pred = model.predict(x_test)

In [55]:
confusion_matrix(y_test,y_test_pred)

array([[44, 14],
       [30, 14]], dtype=int64)

In [58]:
accuracy_score(y_test,y_test_pred)

0.5686274509803921